name: Gunadarma News Scraper

on:
  schedule:
    - cron: '0 0,7,13 * * *' # Berjalan otomatis jam 7 pagi, 2 siang, dan 8 malam WIB
  workflow_dispatch: # Mengaktifkan tombol "Run workflow" manual di web GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Google Chrome Stable
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: stable

    - name: Cache Pip Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Run Scraper Engine
      env:
        BAAK_WEBHOOK: ${{ secrets.BAAK_WEBHOOK }}
        LEPKOM_WEBHOOK: ${{ secrets.LEPKOM_WEBHOOK }}
        STUDENTSITE_WEBHOOK: ${{ secrets.STUDENTSITE_WEBHOOK }}
        CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
      run: |
        python main.py